name: Build and deploy ASP.Net Core app to Azure Web App - chat-console

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build WebGame/NotionWebApp.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish WebGame/NotionWebApp.sln -c Release -o "./myapp"

      - name: List published files
        run: |
          echo "Listing published files:"
          ls -alh ./myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app-${{ github.run_id }}  # Use unique artifact name
          path: ./myapp  # Adjusted path to use relative path

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app-${{ needs.build.outputs.artifact-name }}  # Use the same unique name

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chat-console'
          slot-name: 'production'
          package: .  # Ensure this points to the correct package path
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_1234 }}
